aggregation: FedAvg
attack_client: None
attack_epochs: 10
attack_server: fang
backdoor_config: configs/backdoor_tasks/cifar10_params.yaml
backdoor_type: 9-pixel
batch_size: 32
clients_per_round: 10
cluster: false
cluster_stored_rounds: 10
cuda: false
data_sampler: uniform
data_sampler_args:
- 2
- 42
dataset_name: cifar10
defense: myWBC-clip
epochs: 10
experiment_prefix: Attack_and_Defense_Random
mal_boost: 1
mal_clients_per_round: 2
net_name: Cifar10CNN
num_clients: 100
num_mal_clients: 25
offload_stategy: deadline
output_location: output
pert_strength: 0.2
regular_weight: 0.15
rounds: 80
selection_method: random
single_machine: true
tensor_board_active: true
use_wandb: true
wait_for_clients: true
