batch_size: 32
epochs: 10
rounds: 100
num_clients: 100
num_mal_clients: 10
attack_epochs: 10
selection_method: "periodic"
mal_clients_per_round: 1
clients_per_round: 10
mal_boost: 5
wait_for_clients: true
dataset_name: 'fashion-mnist' # 'cifar10' || 'fashion-mnist' || 'mnist'
net_name: "FashionMNISTCNN" # "Cifar10CNN" || "MNISTCNN" || "FashionMNISTCNN"
# Use cuda is available; setting to false will force CPU
#defense: 'WBC'
attack_server: 'fang' # 'fang' || 'lie'
# attack_client: 'Backdoor'
regular_weight: 0.1
pert_strength: 0.1
cuda: false
experiment_prefix: 'Periodic'
offload_stategy: deadline
output_location: 'output'
tensor_board_active: true
single_machine: true
use_wandb: true
aggregation: 'FedAvg' # 'FedAvg' || 'multiKrum' || 'trmean' || 'median' || 'krum'
sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
#sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
sampler_args:
  - 0.07     # label limit || q probability || alpha || unused
  - 42    # random seed || random seed || random seed || unused
backdoor_config: 'configs/backdoor_tasks/mnist_params.yaml'
