aggregation: bulyan
attack_client: Backdoor
attack_epochs: 10
backdoor_config: configs/backdoor_tasks/mnist_params_pattern.yaml
backdoor_type: 9-pixel
batch_size: 32
clients_per_round: 10
cuda: false
dataset_name: fashion-mnist
defense: WBC
epochs: 10
experiment_prefix: Attack_and_Defense_pattern
mal_boost: 1
mal_clients_per_round: 5
net_name: FashionMNISTCNN
num_clients: 100
num_mal_clients: 10
offload_stategy: deadline
output_location: output
pert_strength: 0.2
regular_weight: 0.4
rounds: 80
sampler: uniform
sampler_args:
- 0.07
- 42
selection_method: periodic
single_machine: true
tensor_board_active: true
use_wandb: true
wait_for_clients: true
